export const LIMITS = {
  // Plan limits
  FREE: {
    MAX_CARDS: 200,
    MAX_OCR_SCANS_PER_MONTH: 30,
    MAX_FOLDERS: 5,
    MAX_TAGS: 10,
    EXPORT_SINGLE_ONLY: true,
  },
  PRO: {
    MAX_CARDS: Infinity,
    MAX_OCR_SCANS_PER_MONTH: Infinity,
    MAX_FOLDERS: Infinity,
    MAX_TAGS: Infinity,
    EXPORT_SINGLE_ONLY: false,
  },

  // Common limits
  MAX_TAGS_PER_CARD: 10,
  MAX_CONTACT_DETAILS_PER_CARD: 20,
  MAX_BATCH_SIZE: 100,
  MAX_FOLDER_DEPTH: 1,
  MAX_CARDS_PER_USER: 50_000,

  // Image
  MAX_IMAGE_SIZE: 10 * 1024 * 1024, // 10MB
  THUMBNAIL_SIZE: 200,
  ORIGINAL_MAX_DIMENSION: 2048,

  // Search
  SEARCH_DEBOUNCE_MS: 300,
  MAX_RECENT_SEARCHES: 10,

  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,

  // Auth
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_LOCKOUT_MINUTES: 15,
  ACCESS_TOKEN_EXPIRY_MINUTES: 15,
  REFRESH_TOKEN_EXPIRY_DAYS: 7,
  PASSWORD_RESET_EXPIRY_HOURS: 1,
  EMAIL_VERIFY_EXPIRY_HOURS: 24,

  // Password
  MIN_PASSWORD_LENGTH: 8,

  // Text
  MAX_NAME_LENGTH: 100,
  MAX_COMPANY_LENGTH: 100,
  MAX_JOB_TITLE_LENGTH: 100,
  MAX_ADDRESS_LENGTH: 500,
  MAX_WEBSITE_LENGTH: 500,
  MAX_MEMO_LENGTH: 2000,
  MAX_FOLDER_NAME_LENGTH: 50,
  MAX_TAG_NAME_LENGTH: 30,
  MAX_LABEL_LENGTH: 50,
} as const;
